databases:
  - name: cvdb
    plan: free
    databaseName: cv
    user: mysite

services:
  - type: web
    plan: free
    name: dzmitry
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn my_site_pro.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cvdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4