databases:
  - name: personalsitedb
    plan: free
    databaseName: personalsite
    user: personalsite

services:
  - type: web
    plan: free
    name: dzmitry
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn my_site_pro.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: personalsitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4