# Generated by Django 5.0.7 on 2024-08-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='person_father_id',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='person_mother_id',
        ),
    ]
