# Generated by Django 4.2.14 on 2024-08-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_remove_persons_person_father_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spouses',
            fields=[
                ('marriage_id', models.AutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255)),
                ('status', models.DecimalField(db_column='status', decimal_places=0, max_digits=1)),
                ('edit_date', models.DateTimeField(auto_now=True, db_column='edit_date')),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husbands', to='genealogy.spouses')),
                ('wife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wives', to='genealogy.spouses')),
            ],
            options={
                'db_table': 'spouses',
                'managed': True,
            },
        ),
    ]
