# Generated by Django 4.2.14 on 2024-08-07 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_spouses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spouses',
            new_name='Marriages',
        ),
        migrations.AlterModelTable(
            name='marriages',
            table='marriages',
        ),
    ]
