# Generated by Django 4.2.14 on 2024-08-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_rename_spouses_marriages_alter_marriages_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couples',
            fields=[
                ('couple_id', models.AutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255)),
                ('status', models.DecimalField(db_column='status', decimal_places=0, max_digits=1)),
                ('edit_date', models.DateTimeField(auto_now=True, db_column='edit_date')),
                ('he', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_he', to='genealogy.couples')),
                ('she', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couple_she', to='genealogy.couples')),
            ],
            options={
                'db_table': 'couples',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Marriages',
        ),
    ]
