# Generated by Django 4.2.14 on 2024-08-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_couples_delete_marriages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couples',
            name='he',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='he_set', to='genealogy.persons'),
        ),
        migrations.AlterField(
            model_name='couples',
            name='she',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='she_set', to='genealogy.persons'),
        ),
    ]
